### ISSUE TITLE
Add Translations: German + Russian

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-android-app#104]
- [x] add German translations
- [x] add Russian translations

**Comment by Dianaaiym** [comment]
Done! DE and RU languages

**Comment by esengulov** [comment]
> Done! DE and RU languages

@

> Done! RU and DE languages

please review all translated texts and make sure that that they are release ready

- [ ] English
- [ ] Russian
- [ ] German

**Comment by Dianaaiym** [comment]
done

**Comment by esengulov** [comment]
> done
 ok, we are ready to start with the other languages
please set up a new issues both for iOS/Android for the next 3 languages
