### ISSUE TITLE
Settings: Add About section

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-android-app#196]
- [ ] design layout (@TalgatNurdinov )
- [ ] implement layout ( @rafaelekol )
- [ ] all page text below the "This is a Decentralized App." should be localizable (@rafaelekol )

Page contents:

BANK Wallet

[app logo]

This is a Decentralized App.

**Terms & Privacy:**

Your funds are stored in the BANK wallet app. Not on any external servers.

BANK Wallet doesn't store or collect any private info.

BANK Wallet doesn't depend on any server or person to function.

BANK Wallet works everywhere as long as there is an internet.

It is impossible for a third party to block the wallet from working or to block the user.

The entire code powering the BANK Wallet is free and open to public.

There may be bugs in the code. Make sure you always backup a Secret Key for your wallet!

**Dependencies:**

There are some third-party services used by the BANK Wallet for non-critical data for the wallet.

1) IPFS Decentralized Storage
- stores current exchange rates, 
- stores coin information, 
- stores "recommended" transaction fees
- stores a list of supported base currencies
- stores public blockchain dada

2) CryptoCompare.com - used to obtain current market exchange rates.

3) Etherscan.io - used to retrieve a list of past transactions for a given Ethereum address.

4) Infura.io - a public gateway to Ethereum Blockchain.

**Comment by TalgatNurdinov** [comment]
design
<img width="249" alt="screen shot 2018-10-18 at 3 11 52 pm" src="https://user-images.githubusercontent.com/42367908/47143952-2b917a00-d2e8-11e8-827b-21f2b49d2e77.png">

https://zpl.io/2Gozrqr
