### ISSUE TITLE
Implement Transaction Status screen

### ISSUE THREAD

**Issue by rafaelekol** [horizontalsystems/bank-wallet-android-app#77]
with swipe navigation between addresses

**Comment by esengulov** [comment]
@rafaelekol we don't need to show all addresses in the Transaction bottom dialog, only one FROM address will be displayed. However, we will display a list of all unspent outputs (i.e. all FROMs) in transaction status page. That screen would be accessible from clicking on transaction status button in bottom dialog for transaction.

renamed ticket to "Implement Transaction Status screen". 

@TalgatNurdinov please provide design for Transaction Status

**Comment by TalgatNurdinov** [comment]
duplicate #75
