### ISSUE TITLE
HOME: show info button on non-active currencies.

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/bank-wallet-android-app#98]
"Info" should go to the link to the currency page

![balance empty](https://user-images.githubusercontent.com/42367908/45477199-d7343100-b762-11e8-8c12-68da162c28ef.png)

https://zpl.io/aMvOZAz

**Comment by esengulov** [comment]
Duplicate of #https://github.com/horizontalsystems/bank-wallet-android-app/issues/182
